<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from uk.co.compucorp.civicrm.giftaid/xml/schema/CRM/Civigiftaid/BatchSettings.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:4daf26360583e9cae56bed792cb51f42)
 */
use CRM_Civigiftaid_ExtensionUtil as E;

/**
 * Database access object for the BatchSettings entity.
 */
class CRM_Civigiftaid_DAO_BatchSettings extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '4.4';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_civigiftaid_batchsettings';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique BatchSettings ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Batch
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $batch_id;

  /**
   * Financial type enabled for this batch
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $financial_types_enabled;

  /**
   * Globally enabled for this batch
   *
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $globally_enabled;

  /**
   * Basic rate tax for the batch.
   *
   * @var float|string
   *   (SQL type: decimal(4,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $basic_rate_tax;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_civigiftaid_batchsettings';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Batch Settingses') : E::ts('Batch Settings');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique BatchSettings ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_civigiftaid_batchsettings.id',
          'table_name' => 'civicrm_civigiftaid_batchsettings',
          'entity' => 'BatchSettings',
          'bao' => 'CRM_Civigiftaid_DAO_BatchSettings',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => '4.4',
        ],
        'batch_id' => [
          'name' => 'batch_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Batch ID'),
          'description' => E::ts('FK to Batch'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_civigiftaid_batchsettings.batch_id',
          'table_name' => 'civicrm_civigiftaid_batchsettings',
          'entity' => 'BatchSettings',
          'bao' => 'CRM_Civigiftaid_DAO_BatchSettings',
          'localizable' => 0,
          'FKClassName' => 'CRM_Batch_DAO_Batch',
          'add' => '4.4',
        ],
        'financial_types_enabled' => [
          'name' => 'financial_types_enabled',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Financial Types Enabled'),
          'description' => E::ts('Financial type enabled for this batch'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_civigiftaid_batchsettings.financial_types_enabled',
          'table_name' => 'civicrm_civigiftaid_batchsettings',
          'entity' => 'BatchSettings',
          'bao' => 'CRM_Civigiftaid_DAO_BatchSettings',
          'localizable' => 0,
          'add' => '4.4',
        ],
        'globally_enabled' => [
          'name' => 'globally_enabled',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Globally Enabled'),
          'description' => E::ts('Globally enabled for this batch'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_civigiftaid_batchsettings.globally_enabled',
          'table_name' => 'civicrm_civigiftaid_batchsettings',
          'entity' => 'BatchSettings',
          'bao' => 'CRM_Civigiftaid_DAO_BatchSettings',
          'localizable' => 0,
          'add' => '4.4',
        ],
        'basic_rate_tax' => [
          'name' => 'basic_rate_tax',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Basic Rate Tax'),
          'description' => E::ts('Basic rate tax for the batch.'),
          'required' => TRUE,
          'precision' => [
            4,
            2,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_civigiftaid_batchsettings.basic_rate_tax',
          'table_name' => 'civicrm_civigiftaid_batchsettings',
          'entity' => 'BatchSettings',
          'bao' => 'CRM_Civigiftaid_DAO_BatchSettings',
          'localizable' => 0,
          'add' => '4.4',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'civigiftaid_batchsettings', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'civigiftaid_batchsettings', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
