-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from file:drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_civigiftaid_batchsettings`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_civigiftaid_batchsettings
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_civigiftaid_batchsettings` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique BatchSettings ID',
  `batch_id` int unsigned COMMENT 'FK to Batch',
  `financial_types_enabled` text COMMENT 'Financial type enabled for this batch',
  `globally_enabled` tinyint COMMENT 'Globally enabled for this batch',
  `basic_rate_tax` decimal(4,2) NOT NULL COMMENT 'Basic rate tax for the batch.',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_civigiftaid_batchsettings_batch_id FOREIGN KEY (`batch_id`) REFERENCES `civicrm_batch`(`id`) ON DELETE CASCADE)
ENGINE=InnoDB;
